baseURL = 'https://hermann.life/'
languageCode = 'en-us'
title = 'Vincent @Alixir'
theme = 'hugo-alixir'

paginate = 20 

[services]
[services.disqus]
disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Hermann Vincent"
  info = "Application Designer and Developer"
  description = "Hermann Vincent's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "https://media.licdn.com/dms/image/D4E03AQF3oJdSXNX1ig/profile-displayphoto-shrink_800_800/0/1686059782578?e=1723075200&v=beta&t=znelBLpzjJtK6hhVLNEsDgxTj9Ug8K7Aa1ChmiRAFBY"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/vincent-alxr/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/vincent-hermann-68b4ba211/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.projects]]
  name = "Projects"
  weight = 3
  url = "projects/"